// @Here is the automation code for Login form for dev.planet.com .   
/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
      // should go to the Login URL on Bigteams Shedule Star 
      cy.visit('https://schedulestar-test.bigteams.com/login/')
        .wait(2000)
})
it('Should go to the Login Page and Login for the new User', () => {
    cy.get('#username').click().type('shahbaz.khan@cache-cloud.com')
      .wait(2000)
      .get('#password').click().type('Banana11')
      .wait(2000)
      .get('label > .fa').click()
      .wait(2000)
      .get('.panel-body > .btn').click()
      .wait(2000)
      .get('#buttonbar_add').click()
      .wait(2000)
      .get('#pnlSportsDetailsAnchor').click()
      .wait(2000)
      .get('#selStartHour_s').option('span').contains('1').click()
      .wait(2000)
      .get('#selStartMin_s').option('span').contains('05').click()
      .wait(2000)
      .get('#selStartAmpm_s').option('span').contains('AM').click()
      .wait(2000)
      .get('#select2-selTeamSeasonPicker_s-container').click()
      .wait(2000)
      .get('#selGameType').click()
      .wait(2000)
      .get('#txtEventTitle_s').click()
      .wait(2000)
      .get('#chkTentative_s').click()
      .wait(2000)
      .get('#selArrivalHour_s').click()
      .wait(2000)
      .get('#selArrivalMin_s').click()
      .wait(2000)
      .get('#selArrivalMin_s').click()
      .wait(2000)
      .get('#selArrivalAmpm_s').click()
      .wait(2000)
      .get('#homeaway_s_Away').click()
      .wait(2000)
      .get('#addOpponentList_chosen > .chosen-single > span').find('span').contains('OPEN DATE')
  })
})