/// <reference types="cypress" />

describe('Login', () => {
    
    beforeEach(() => {
        // should go to the Login URL on Bigteams Shedule Star Student Central  
        cy.visit('https://www.dev.planeths.com/index.php?keyword=/user/settings/notifications')
        //.wait(2000)
        //.get('#user-email-mobile').click().type('testone@yopmail.com')
        //.wait(2000)
        //.get('#user-password').click().type('abc12345')
        .wait(2000)
        //.get('.buttons > .action-btn-group-btn').click()
    })
//Negative Test Case 0
   it('Should go to Sign-Up Page skip some steps', () => {
      cy.visit('https://dev.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3Dadmin%2520home')
        .wait(2000)
        .get(':nth-child(2) > .row > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label').click()
        .wait(2000)
        .get('#user-first-name').click().type('Shahbaz')
        .wait(2000)
        .get('#user-last-name').click().type('Khan')
        .wait(2000)
        .get('#user-email-mobile').click().type('shahbaz.khan@cache-cloud.com')
        .wait(2000)
        .get('#user-password').click().type('gggg')
        .wait(2000)
        .get('#user-password-confirm').click().type('564gvf')
        .wait(2000)
        .get('#school_id_txt').click().type('abc test school')   
        .wait(2000)
        .get('.inner-content').click()   
    })
    // Negative Test Case 1
    it('Should go to Sign-Up Page an enter wrong Email and Password', () => {
        cy.visit('https://dev.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3Dadmin%2520home')
          .wait(2000)
          .get(':nth-child(2) > .row > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label').click()
          .wait(2000)
          .get('#user-first-name').click().type('Shahbaz')
          .wait(2000)
          .get('#user-last-name').click().type('Khan')
          .wait(2000)
          .get('#user-email-mobile').click().type('srfgsgfsfd')
          .wait(2000)
          .get('#user-password').click().type('gggg')
          .wait(2000)
          .get('#user-password-confirm').click().type('564gvf')
          .wait(2000)
          .get('#school_id_txt').click().type('abc test school')   
          .wait(2000)
          .get('.inner-content').click()   
      })
      // Negative Test Case 2 
      it('Should go to Sign-Up Page an enter wrong First Name and Last name', () => {
        cy.visit('https://dev.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3Dadmin%2520home')
          .wait(2000)
          .get(':nth-child(2) > .row > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label').click()
          .wait(2000)
          .get('#user-first-name').click().type('65324625136452356424z')
          .wait(2000)
          .get('#user-last-name').click().type('234234234324234234')
          .wait(2000)
          .get('#user-email-mobile').click().type('srfgsgfsfd')
          .wait(2000)
          .get('#user-password').click().type('gggg')
          .wait(2000)
          .get('#user-password-confirm').click().type('564gvf')
          .wait(2000)
          .get('#school_id_txt').click().type('abc test school')   
          .wait(2000)
          .get('.inner-content').click()   
      })

       // Negative Test Case 2 
       it('Should go to Sign-Up Page an enter wrong First Name and Last name', () => {
        cy.visit('https://dev.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3Dadmin%2520home')
          .wait(2000)
          .get(':nth-child(2) > .row > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label').click()
          .wait(2000)
          .get('#user-first-name').click().type('65324625136452356424z')
          .wait(2000)
          .get('#user-last-name').click().type('234234234324234234')
          .wait(2000)
          .get('#user-email-mobile').click().type('srfgsgfsfd')
          .wait(2000)
          .get('#user-password').click().type('gggg')
          .wait(2000)
          .get('#user-password-confirm').click().type('564gvf')
          .wait(2000)
          .get('#school_id_txt').click().type('764376476734673647346')   
          .wait(2000)
          .get('.inner-content').click()   
      })

      it('Should go to Sign-Up and click directly to click button', () => {
        cy.visit('https://dev.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3Dadmin%2520home')
          .wait(2000)
          .get('.inner-content').click()   
      })
})