/// <reference types="cypress" />

describe('Sign-Up', () => {
    beforeEach(() => {
      // should go to the Login URL on Bigteams Shedule Star 
      cy.visit('https://test.planeths.com/index.php?keyword=/user/signup&schoolID=2011&next=%2Findex.php%3Fkeyword%3DAdmin%2520User%2520Edit')
        .wait(2000)
})
it('should go to the element Username and Password field', () => {
    cy.get(':nth-child(2) > .row > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label > input').click()
      .wait(2000)
      .get('#user-first-name').click().type('Test User')
      .wait(2000)
      .get('#user-last-name').click().type('Test User')
      .wait(2000)
      .get(':nth-child(4) > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label > input')
      .wait(2000)
      .get(':nth-child(4) > .col-xs-12 > .validate-group > .form-group > :nth-child(2) > label').click()
      .wait(2000)
      .get('#user-birthdate-month').select('Jan')  //.should('have.value', 'Jan')
      .wait(2000)
      .get('#user-birthdate-day').select('1')  //.should('have.value', '1')
      .wait(2000)
      .get('#user-birthdate-year').select('2011')  //.should('have.value', '2011')
      .wait(2000)
      .get('#user-grad-year').select('2021')
      .wait(3000)
      .get('#user-email-mobile').click().type('test7@yopmail.com')
      .wait(2000)
      .get('#user-password').click().type('123')
      .wait(2000)
      .get('#user-password-confirm').click().type('123')
      .wait(1000)
      .get('#school_id_txt').type('AB')
      .get('#ui-id-1').find('li').contains('ABBEVILLE HIGH (ABBEVILLE, SC)').click()
      .wait(3000)
      .get('#user-teams-container > div:nth-child(1) > div > div > div > div.panel-body > div > div:nth-child(1)').click()
      .wait(2000)
      .get('#action-btn-group > div.buttons > button > div > div.text-wrapper.desktop-text').click()
      .wait(2000)
      .get('body > div.themeV2Top.hidden-print > div > nav.row.desktop.visible-md.visible-lg.hidden-print > div > div > div.btn-group.hidden-print.open > button').click()  
  })
  afterEach(() => {
    cy.logout()
  })
})