//@automation code for the Bigteams Fan Central Site. Here we go. Module #1   
/// <reference types="cypress" />

describe('SignUp', () => {
    //Before Hook to fetch the URL before script 
    beforeEach(() => {
      // should go to the Bigteams Fan Central Dev Admin Site / Fetching the data from URL
      cy.visit('https://dev.bigteams.com/auth/new')
        //Putting assertion on URL to check the URL text. 
        .url().should('include', 'dev.bigteams.com')
        .wait(5000)
        .get('.close > span').click()
        .wait(2000)

        // https://on.cypress.io/as
        // Alias a DOM element for use later
        // We don't have to traverse to the element
        // later in our code, we reference it with @
        // Clearing the cache from browser        
})

//This Test case should verify the Validation errors on the Sign Up form with Student - Negative Test Case
it('Should go to Sign-Up and Should test validation errors on "Mandatory Fields"', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Student')
    .wait(2000)
    .get('#myFirstName').click().type('54625356253465')
    .wait(3000)
    .get('#myLastName').click().type('6462346346364')
    .wait(3000)
    .get('#myEmailAddress').click().type('ghdgdfggf')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('2345234524545')
    .wait(2000)
    .get('#myPostalCode').click().type('46000786')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('abc123')
    .wait(2000)
    .get('#confirmPassword').click().type('abc123')
    .wait(2000)
    .get('#armyNGOptInNo').click()
    .wait(2000)
    .get('#angOptInNo').click()
    .wait(2000)
    .get('#ncsaOptInYes').click()
    .wait(2000)
    .get('#btnCreateAccount').click()
    .wait(3000)
    .get('#ncsaFrm_parent1FirstName').click().type('565642634543')
    .wait(2000)
    .get('#ncsaFrm_parent1LastName').click().type('234234234234')
    .wait(2000)
    .get('#ncsaFrm_parent1Email').click().type('testFC')
    .wait(2000)
    .get('#ncsaFrm_parent1Phone').click().type('23423423434')
    .wait(2000)
    .get('#ncsaFrm_studentGraduationYear').select('2022')
    .wait(2000)
    .get('#ncsaFrm_studentSportID').select('Football')
    .wait(2000)
    .get('.col-sm-12 > .btn-primary').click()
    .wait(2000)
    .get('#currentPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('.btn-primary').click()
    .wait(2000)
 })

//This test case should directly login with the new Student 
 it('Should go to Sign Up and Login with New Student"', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Student')
    .wait(2000)
    .get('#myFirstName').click().type('54625356253465')
    .wait(3000)
    .get('#myLastName').click().type('Test shahbaz')
    .wait(3000)
    .get('#myEmailAddress').click().type('testFC10@yopmail.com')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('5463728296')
    .wait(2000)
    .get('#myPostalCode').click().type('46000')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#armyNGOptInNo').click()
    .wait(2000)
    .get('#angOptInNo').click()
    .wait(2000)
    .get('#ncsaOptInYes').click()
    .wait(2000)
    .get('#btnCreateAccount').click()
    .wait(3000)
    .get('#ncsaFrm_parent1FirstName').click().type('Shahbaz Ali Khan')
    .wait(2000)
    .get('#ncsaFrm_parent1LastName').click().type('Test FC Site')
    .wait(2000)
    .get('#ncsaFrm_parent1Email').click().type('testFC@yopmail.com')
    .wait(2000)
    .get('#ncsaFrm_parent1Phone').click().type('123-456-7898')
    .wait(2000)
    .get('#ncsaFrm_studentGraduationYear').select('2022')
    .wait(2000)
    .get('#ncsaFrm_studentSportID').select('Football')
    .wait(2000)
    .get('.col-sm-12 > .btn-primary').click()
    .wait(2000)
    .get('#currentPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA***007n')
    .wait(2000)
    .get('.btn-primary').click()
    .wait(2000)
 })

//This Test Case for Coach // Negative Test Case 1
 it('Putting the First and Last Name Fields Wrong', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Coach')
    .wait(2000)
    .get('#myFirstName').click().type('3412341234232')
    .wait(3000)
    .get('#myLastName').click().type('655162543126')
    .wait(3000)
    .get('#myEmailAddress').click().type('testFC15@yopmail.com')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('8767876543')
    .wait(2000)
    .get('#myPostalCode').click().type('56743')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA**')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA**')
    .wait(3000)
    .get('#btnCreateAccount').click()
    .wait(2000)
 })

 //This Test Case for Coach // Negative Test Case 2
 it('Putting the wrong Phone Number and Email Address in the fields', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Coach')
    .wait(2000)
    .get('#myFirstName').click().type('Shahbaz Test')
    .wait(3000)
    .get('#myLastName').click().type('Khan')
    .wait(3000)
    .get('#myEmailAddress').click().type('34234234')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('hgfdgfsgadffs')
    .wait(2000)
    .get('#myPostalCode').click().type('56743')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA')
    .wait(3000)
    .get('#btnCreateAccount').click()
    .wait(2000)
 })

 //This Test Case for Coach // Negative Test Case 3 
 it('Putting the wrong Password', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Coach')
    .wait(2000)
    .get('#myFirstName').click().type('Shahbaz Test')
    .wait(3000)
    .get('#myLastName').click().type('Khan')
    .wait(3000)
    .get('#myEmailAddress').click().type('34234234')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('hgfdgfsgadffs')
    .wait(2000)
    .get('#myPostalCode').click().type('56743')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA')
    .wait(3000)
    .get('#btnCreateAccount').click()
    .wait(2000)
 })

 //Positive Test Case for Coach
 it('Verifying the First and Last Name fields only accept characters', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Coach')
    .wait(2000)
    .get('#myFirstName').click().type('3412341234232')
    .wait(3000)
    .get('#myLastName').click().type('655162543126')
    .wait(3000)
    .get('#myEmailAddress').click().type('testFC10@yopmail.com')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('8767876543')
    .wait(2000)
    .get('#myPostalCode').click().type('56743')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA')
    .wait(3000)
    .get('#btnCreateAccount').click()
    .wait(2000)
 })

 //Positive test case User will Sign-Up to the system directly 
 it('User will Sign Up to the system with Coach', () => {
  cy.wait(1000)
    .get('#myUserRole').select('Coach')
    .wait(2000)
    .get('#myFirstName').click().type('Test Account Aut')
    .wait(3000)
    .get('#myLastName').click().type('Khan')
    .wait(3000)
    .get('#myEmailAddress').click().type('testFC1@yopmail.com')
    .wait(2000)
    .get('#myMobilePhoneNumber').click().type('8767876543')
    .wait(2000)
    .get('#myPostalCode').click().type('56743')
    .wait(2000)
    .get('#mygraduationYear').select('2021')
    .wait(2000)
    .get('#newPassword').click().type('IBF@CBA')
    .wait(2000)
    .get('#confirmPassword').click().type('IBF@CBA')
    .wait(3000)
    .get('#btnCreateAccount').click()
    .wait(2000)
 })

//  //Entered Password should 
//  it('Should go to the Sign Up and Form must not accept the First Name and Last Name must not accept the numbers or special characters', () => {
//   cy.wait(1000)
//     .get('#myUserRole').select('Student')
//     .wait(2000)
//     .get('#myFirstName').click().type('Shahbaz Khan')
//     .wait(3000)
//     .get('#myLastName').click().type('Khan')
//     .wait(3000)
//     .get('#myEmailAddress').click().type('testFC9@yopmail.com')
//     .wait(2000)
//     .get('#myMobilePhoneNumber').click().type('546372829634321234')
//     .wait(2000)
//     .get('#myPostalCode').click().type('460001234123')
//     .wait(2000)
//     .get('#mygraduationYear').select('2021')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#armyNGOptInNo').click()
//     .wait(2000)
//     .get('#angOptInNo').click()
//     .wait(2000)
//     .get('#ncsaOptInYes').click()
//     .wait(2000)
//     .get('#btnCreateAccount').click()
//     .wait(3000)
//     .get('#ncsaFrm_parent1FirstName').click().type('Shahbaz Ali Khan')
//     .wait(2000)
//     .get('#ncsaFrm_parent1LastName').click().type('Test FC Site')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Email').click().type('testFC@yopmail.com')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Phone').click().type('123-456-7898')
//     .wait(2000)
//     .get('#ncsaFrm_studentGraduationYear').select('2022')
//     .wait(2000)
//     .get('#ncsaFrm_studentSportID').select('Football')
//     .wait(2000)
//     .get('.col-sm-12 > .btn-primary').click()
//     .wait(2000)
//     .get('#currentPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('.btn-primary').click()
//     .wait(2000) 
//  })

//  it('Should verify the application only accept Valid and Properly formated Email', () => {
//   cy.wait(1000)
//     .get('#myUserRole').select('Student')
//     .wait(2000)
//     .get('#myFirstName').click().type('3412341234232')
//     .wait(3000)
//     .get('#myLastName').click().type('655162543126')
//     .wait(3000)
//     .get('#myEmailAddress').click().type('testFC9@yopmail.com')
//     .wait(2000)
//     .get('#myMobilePhoneNumber').click().type('546372829634321234')
//     .wait(2000)
//     .get('#myPostalCode').click().type('460001234123')
//     .wait(2000)
//     .get('#mygraduationYear').select('2021')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#armyNGOptInNo').click()
//     .wait(2000)
//     .get('#angOptInNo').click()
//     .wait(2000)
//     .get('#ncsaOptInYes').click()
//     .wait(2000)
//     .get('#btnCreateAccount').click()
//     .wait(3000)
//     .get('#ncsaFrm_parent1FirstName').click().type('Shahbaz Ali Khan')
//     .wait(2000)
//     .get('#ncsaFrm_parent1LastName').click().type('Test FC Site')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Email').click().type('testFC@yopmail.com')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Phone').click().type('123-456-7898')
//     .wait(2000)
//     .get('#ncsaFrm_studentGraduationYear').select('2022')
//     .wait(2000)
//     .get('#ncsaFrm_studentSportID').select('Football')
//     .wait(2000)
//     .get('.col-sm-12 > .btn-primary').click()
//     .wait(2000)
//     .get('#currentPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('.btn-primary').click()
//     .wait(2000) 
//  })

//  it('Should verify the application only accept Valid and Properly formated Email', () => {
//   cy.wait(1000)
//     .get('#myUserRole').select('Student')
//     .wait(2000)
//     .get('#myFirstName').click().type('3412341234232')
//     .wait(3000)
//     .get('#myLastName').click().type('655162543126')
//     .wait(3000)
//     .get('#myEmailAddress').click().type('testFC9@yopmail.com')
//     .wait(2000)
//     .get('#myMobilePhoneNumber').click().type('546372829634321234')
//     .wait(2000)
//     .get('#myPostalCode').click().type('460001234123')
//     .wait(2000)
//     .get('#mygraduationYear').select('2021')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA')
//     .wait(2000)
//     .get('#armyNGOptInNo').click()
//     .wait(2000)
//     .get('#angOptInNo').click()
//     .wait(2000)
//     .get('#ncsaOptInYes').click()
//     .wait(2000)
//     .get('#btnCreateAccount').click()
//     .wait(3000)
//     .get('#ncsaFrm_parent1FirstName').click().type('Shahbaz Ali Khan')
//     .wait(2000)
//     .get('#ncsaFrm_parent1LastName').click().type('Test FC Site')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Email').click().type('testFC@yopmail.com')
//     .wait(2000)
//     .get('#ncsaFrm_parent1Phone').click().type('123-456-7898')
//     .wait(2000)
//     .get('#ncsaFrm_studentGraduationYear').select('2022')
//     .wait(2000)
//     .get('#ncsaFrm_studentSportID').select('Football')
//     .wait(2000)
//     .get('.col-sm-12 > .btn-primary').click()
//     .wait(2000)
//     .get('#currentPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#newPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('#confirmPassword').click().type('IBF@CBA***007n')
//     .wait(2000)
//     .get('.btn-primary').click()
//     .wait(2000) 
//  })
})
//})